/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoumissionRouteImport } from './routes/soumission'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConditionsUtilisationRouteImport } from './routes/conditions-utilisation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminBlogLoginRouteImport } from './routes/admin/blog/login'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'

const SoumissionRoute = SoumissionRouteImport.update({
  id: '/soumission',
  path: '/soumission',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsUtilisationRoute = ConditionsUtilisationRouteImport.update({
  id: '/conditions-utilisation',
  path: '/conditions-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogLoginRoute = AdminBlogLoginRouteImport.update({
  id: '/admin/blog/login',
  path: '/admin/blog/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/soumission': typeof SoumissionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/login': typeof AdminBlogLoginRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/soumission': typeof SoumissionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/login': typeof AdminBlogLoginRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog': typeof AdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/soumission': typeof SoumissionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/login': typeof AdminBlogLoginRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions-utilisation'
    | '/confidentialite'
    | '/soumission'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
    | '/admin/blog/$id'
    | '/admin/blog/login'
    | '/admin/blog/new'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions-utilisation'
    | '/confidentialite'
    | '/soumission'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog'
    | '/services'
    | '/admin/blog/$id'
    | '/admin/blog/login'
    | '/admin/blog/new'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/conditions-utilisation'
    | '/confidentialite'
    | '/soumission'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
    | '/admin/blog/$id'
    | '/admin/blog/login'
    | '/admin/blog/new'
    | '/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsUtilisationRoute: typeof ConditionsUtilisationRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  SoumissionRoute: typeof SoumissionRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogLoginRoute: typeof AdminBlogLoginRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soumission': {
      id: '/soumission'
      path: '/soumission'
      fullPath: '/soumission'
      preLoaderRoute: typeof SoumissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-utilisation': {
      id: '/conditions-utilisation'
      path: '/conditions-utilisation'
      fullPath: '/conditions-utilisation'
      preLoaderRoute: typeof ConditionsUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/login': {
      id: '/admin/blog/login'
      path: '/admin/blog/login'
      fullPath: '/admin/blog/login'
      preLoaderRoute: typeof AdminBlogLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsUtilisationRoute: ConditionsUtilisationRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  SoumissionRoute: SoumissionRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogLoginRoute: AdminBlogLoginRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
